export const course = {
  "sections": [
    {
      "id": "map",
      "label": "Map",
      "key": "cover",
      "start": 1,
      "end": 2,
      "title": "Overview",
      "question": "Follow the argument",
      "example": "Navigation → bandit → episode"
    },
    {
      "id": "mdp",
      "label": "MDP",
      "key": "model",
      "start": 3,
      "end": 17,
      "title": "Define the task",
      "question": "What should the agent maximize?",
      "example": "Navigation"
    },
    {
      "id": "policy",
      "label": "Policy",
      "key": "objective_choice",
      "start": 18,
      "end": 23,
      "title": "Represent the policy",
      "question": "What do the parameters control?",
      "example": "Tables and shared models"
    },
    {
      "id": "reinforce",
      "label": "REINFORCE",
      "key": "landscape",
      "start": 24,
      "end": 36,
      "title": "Learn from samples",
      "question": "How do we estimate a gradient?",
      "example": "One-decision bandit"
    },
    {
      "id": "episodes",
      "label": "Episodes",
      "key": "episode_bridge",
      "start": 37,
      "end": 44,
      "title": "Extend to trajectories",
      "question": "Which return weights each action?",
      "example": "A short recorded episode"
    },
    {
      "id": "baselines",
      "label": "Baselines",
      "key": "evaluation",
      "start": 45,
      "end": 52,
      "title": "Reduce gradient noise",
      "question": "Why can centering help?",
      "example": "Return to the same bandit"
    },
    {
      "id": "ppo",
      "label": "PPO",
      "key": "why_ppo",
      "start": 53,
      "end": 61,
      "title": "Reuse recent experience",
      "question": "Why limit policy changes?",
      "example": "Ratios and clipping"
    },
    {
      "id": "appendix",
      "label": "Appendix",
      "key": "appendix_start",
      "start": 62,
      "end": 92,
      "title": "Optional reference",
      "question": "Why do the estimators work?",
      "example": "Proofs and code"
    }
  ],
  "pages": {
    "cover": 1,
    "roadmap": 2,
    "model": 3,
    "navigation": 4,
    "interaction": 5,
    "learning_feedback": 6,
    "transition_reward": 7,
    "policy": 8,
    "objective": 9,
    "grid_objective": 10,
    "markov_words": 11,
    "markov_mdp": 12,
    "state_food": 13,
    "reward_return": 14,
    "reward_design": 15,
    "discount_definition": 16,
    "discount_explorer": 17,
    "objective_choice": 18,
    "parameterized_policy": 19,
    "table_limits": 20,
    "shared_approximation": 21,
    "policy_equations": 22,
    "policy_model": 23,
    "landscape": 24,
    "pg_idea": 25,
    "what_reinforce": 26,
    "bandit": 27,
    "sigmoid_policy": 28,
    "known_J": 29,
    "one_step_rule": 30,
    "score_derivatives": 31,
    "sample_update": 32,
    "batch": 33,
    "demo": 34,
    "on_policy": 35,
    "old_batch_bias": 36,
    "episode_bridge": 37,
    "episode_trace": 38,
    "episode_rule": 39,
    "episode_numbers": 40,
    "return_to_go": 41,
    "backward_returns": 42,
    "loss": 43,
    "code": 44,
    "evaluation": 45,
    "baseline_recap": 46,
    "baseline_why": 47,
    "variance_math": 48,
    "baseline_variance": 49,
    "variance_batch": 50,
    "baseline_rule": 51,
    "critic": 52,
    "why_ppo": 53,
    "ppo_local": 54,
    "advantage": 55,
    "ppo_ratio": 56,
    "ppo_clip": 57,
    "kl_main": 58,
    "ppo_loop": 59,
    "project": 60,
    "check": 61,
    "appendix_start": 62,
    "conditional_mean": 63,
    "total_expectation": 64,
    "total_expectation_proof": 65,
    "proof_one_action": 66,
    "proof_sample_reward": 67,
    "proof_sigmoid": 68,
    "unbiased_check": 69,
    "proof_trajectory": 70,
    "trajectory_factors": 71,
    "proof_trajectory_score": 72,
    "proof_goal": 73,
    "proof_score_zero": 74,
    "proof_baseline": 75,
    "proof_numeric": 76,
    "baseline_variance_proof": 77,
    "baseline_restriction": 78,
    "rtg_proof": 79,
    "discounted_pg": 80,
    "tail_horizon": 81,
    "is_identity": 82,
    "is_bandit": 83,
    "is_trajectory": 84,
    "ppo_surrogate": 85,
    "ppo_formula": 86,
    "kl_math": 87,
    "kl_reference": 88,
    "gae": 89,
    "algorithm": 90,
    "notation": 91,
    "sources": 92
  },
  "total": 92,
  "main": 61
};
