export const course = {
  "sections": [
    {
      "id": "map",
      "label": "Map",
      "key": "cover",
      "start": 1,
      "end": 2,
      "title": "Overview",
      "question": "Follow the argument",
      "example": "Navigation → bandit → episode"
    },
    {
      "id": "mdp",
      "label": "MDP",
      "key": "model",
      "start": 3,
      "end": 15,
      "title": "Define the task",
      "question": "What should the agent maximize?",
      "example": "Definitions, then navigation"
    },
    {
      "id": "policy",
      "label": "Policy",
      "key": "objective_choice",
      "start": 16,
      "end": 21,
      "title": "Represent the policy",
      "question": "What do the parameters control?",
      "example": "Tables and shared models"
    },
    {
      "id": "reinforce",
      "label": "REINFORCE",
      "key": "landscape",
      "start": 22,
      "end": 35,
      "title": "Learn from samples",
      "question": "How do we estimate a gradient?",
      "example": "One-decision bandit"
    },
    {
      "id": "episodes",
      "label": "Episodes",
      "key": "episode_bridge",
      "start": 36,
      "end": 41,
      "title": "Extend to trajectories",
      "question": "Which return weights each action?",
      "example": "A short recorded episode"
    },
    {
      "id": "baselines",
      "label": "Baselines",
      "key": "baseline_rule",
      "start": 42,
      "end": 43,
      "title": "Center the return",
      "question": "What do value and advantage mean?",
      "example": "Baseline and advantage definitions"
    },
    {
      "id": "ppo",
      "label": "PPO",
      "key": "why_ppo",
      "start": 44,
      "end": 48,
      "title": "Reuse recent experience",
      "question": "Why limit policy changes?",
      "example": "Ratios and clipping"
    },
    {
      "id": "appendix",
      "label": "Appendix",
      "key": "appendix_start",
      "start": 49,
      "end": 79,
      "title": "Optional reference",
      "question": "Why do the estimators work?",
      "example": "Proofs and code"
    }
  ],
  "pages": {
    "cover": 1,
    "roadmap": 2,
    "model": 3,
    "navigation": 8,
    "interaction": 4,
    "transition_reward": 3,
    "policy": 5,
    "objective": 6,
    "markov_words": 7,
    "markov_mdp": 10,
    "state_food": 11,
    "reward_return": 9,
    "reward_design": 15,
    "discount_definition": 12,
    "discount_explorer": 13,
    "objective_choice": 16,
    "parameterized_policy": 17,
    "table_limits": 18,
    "shared_approximation": 19,
    "policy_equations": 20,
    "policy_model": 21,
    "landscape": 22,
    "pg_idea": 23,
    "what_reinforce": 24,
    "bandit": 25,
    "sigmoid_policy": 27,
    "known_J": 28,
    "one_step_rule": 29,
    "score_derivatives": 30,
    "sample_update": 31,
    "batch": 32,
    "demo": 33,
    "on_policy": 34,
    "old_batch_bias": 35,
    "episode_bridge": 36,
    "episode_trace": 37,
    "episode_rule": 38,
    "return_to_go": 39,
    "loss": 40,
    "code": 41,
    "baseline_rule": 42,
    "critic": 43,
    "why_ppo": 44,
    "ppo_local": 45,
    "advantage": 47,
    "ppo_ratio": 46,
    "ppo_clip": 48,
    "appendix_start": 49,
    "conditional_mean": 50,
    "total_expectation": 51,
    "total_expectation_proof": 52,
    "proof_one_action": 53,
    "proof_sample_reward": 54,
    "proof_sigmoid": 55,
    "unbiased_check": 56,
    "proof_trajectory": 57,
    "trajectory_factors": 58,
    "proof_trajectory_score": 59,
    "proof_goal": 60,
    "proof_score_zero": 61,
    "proof_baseline": 62,
    "proof_numeric": 63,
    "baseline_variance_proof": 64,
    "baseline_restriction": 65,
    "rtg_proof": 66,
    "discounted_pg": 67,
    "tail_horizon": 68,
    "is_identity": 69,
    "is_bandit": 70,
    "is_trajectory": 71,
    "ppo_surrogate": 72,
    "ppo_formula": 73,
    "kl_math": 74,
    "kl_reference": 75,
    "gae": 76,
    "algorithm": 77,
    "notation": 78,
    "sources": 79,
    "state_value": 26
  },
  "total": 79,
  "main": 48
};
